# Generated by Django 4.0.4 on 2022-04-13 20:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the equipment', max_length=1000)),
                ('manufacture_id', models.CharField(help_text='Unique manufacture number', max_length=13, unique=True, verbose_name='Manufacture')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('coy_name', models.CharField(max_length=100)),
                ('date_of_last_maintainance', models.DateField(blank=True, null=True)),
                ('date_of_next_maintainance', models.DateField(blank=True, null=True, verbose_name='Maintainance')),
            ],
            options={
                'ordering': ['coy_name', 'store_name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a equipment type (e.g. Radio Set)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular equipment across whole institution', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Equipment availability', max_length=1)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.equipment')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.store'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.ManyToManyField(help_text='Select a type for this equipment', to='catalog.type'),
        ),
    ]
