# Generated by Django 4.0.4 on 2022-04-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='EquipmentType',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='type',
            new_name='equipment_type',
        ),
    ]
