# Generated by Django 4.0.4 on 2022-04-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_equipmentinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
