# Generated by Django 4.0.4 on 2022-04-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_equipmentinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set equipment as returned'),)},
        ),
    ]
